### ISSUE TITLE
Update relevant data onsite

### ISSUE THREAD

**Issue by stevde** [satRdays/berlin2020#3]
After completion of #2, we need to update some key pieces of data:

- team members
- ~~date in headline (should not be mentioned for now)~~
- ~~ticket price (should also not be mentioned for now)~~

Once completed we can deploy site to netlify :tada:

**Comment by stevde** [comment]
Date in headline and ticket price are done for now.

**Comment by fubits1** [comment]
Team page is online. https://github.com/satRdays/berlin2020/pull/15

**Comment by fubits1** [comment]
Page has already been deployed. Closing issue now as resolved.
