### ISSUE TITLE
Fix about section

### ISSUE THREAD

**Issue by stevde** [satRdays/berlin2020#7]
Currently the icons in the about section are not showing for all users.

* fix icon issue
* remove anchor tags (they all point to berlin2019, and they're not necessary)

**Comment by fubits1** [comment]
icon issue fixed with https://github.com/satRdays/berlin2020/pull/14
Not able to fix for Netlify preview for now (as we're using an absolute url to fetch the fonts, which is the baseURL, which is not netlify).

**Comment by fubits1** [comment]
all solved with general landing page overhaul; icon preview now also should work with Netlify: https://github.com/satRdays/berlin2020/pull/17
